config/routes.rb
Rails.application.routes.draw do
  get 'game/start'
  get 'game/restart'
  get 'game/close'
  resources :users do
    member do
      get :delete
    end
  end

  root 'users#index'

  get ':controller(/:action(/:id))'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  attr_accessor :played
  def start
    @played = 'X'
  end

  def restart
  end

  def close
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user ? redirect_to(users_path) : render('new')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params) ? redirect_to(users_path) : render('show')
   
  end


  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_path)
  end
  

  private

  def user_params
    # Form Authentication
    params.require(:user)
    # Regulate mass assignment
    .permit(:first_name, :last_name, :email)
    # 1.Instantiate a new user using params from new form
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game/close.html.erb
<h1>Game#close</h1>
<p>Are you sure you want to close the game?</p>

<button><%= link_to('restart ',:action => 'restart') %></button>

<button><%= link_to('Close the Game ',users_path) %></button>

app/views/game/restart.html.erb
<h1>Game#restart</h1>
<p>All changes will be lost</p>
<p>Are you sure you want to re-start the game?</p>

<button><%= link_to('Restart ',:action => 'start') %></button>
<button><%= link_to('Close the game',:action => 'close') %></button>
<button><%= link_to('<<Home ',users_path) %></button>

app/views/game/start.html.erb
<h1>Tic Tac Toe</h1>
<div class="tic-tac-toe">
<% @later = 1%>
<table>
<% 3.times do%>
 <tr>
 <% 3.times do%>
 <td><div class="box" onclick="myFunc(this)" id= <%= @later+=1%> ><%=@played %></div></td>
 <% end%>
 </tr>
<% end %>
</table>
</div>
<div class="game-buttons">
<button><%= link_to('Re-Start the game',:action => 'restart') %></button>

<button><%= link_to('Close the game',:action => 'close') %></button>

<button><%= link_to('<<Home ',users_path) %></button>
</div>
<script>

 function myFunc(elem) {

     elem.innerHTML === 'X' ?  elem.innerHTML = 'O' :  elem.innerHTML = 'X'
      elem.innerHTML === 'X' ?  elem.style.color = 'red' :  elem.style.color = 'black'
     console.log('Clicked this', elem.innerHTML)
    elem.style.animationName = 'example'
    

 }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_forms.html.erb
 <table>
    <tr>
    <th>First name</th>
    <td><%= f.text_field(:first_name) %></td>
    </tr>
     <tr>
    <th>last name</th>
    <td><%= f.text_field(:last_name) %></td>
    </tr>
     <tr>
    <th>Email</th>
    <td> <%= f.text_field(:email) %></td>
    </tr>
</table>

app/views/users/delete.html.erb
<h1>Users#delete</h1>

<%= form_for(@user, :method => 'delete') do |f| %>
<p>Are you sure you want to delete this user?</p>

    <p><%= "Name : #{@user.first_name} #{@user.last_name}"%></p>
    <p><%= "Email : #{@user.email}"%></p>


<div class='form-buttons'>
  <%= f.submit('Delete user')%>
</div>
<% end %>  
<%=link_to('<< Back to list', users_path, :class => 'back_link') %>

app/views/users/edit.html.erb
<h1>Edit your info</h1>
<%= link_to('<< Back to list', users_path) %>
<%= form_for (@user) do |f| %>
<%# Using Partial form for shared html _form%>
<%= render(:partial => 'forms', :locals => {:f => f}) %>
<div class='form-buttons'>
  <%= f.submit('Update user')%>
</div>
<% end %> 

app/views/users/index.html.erb
<h1>Home page</h1>

<h3>These are all the users currently in the Database</h3>
<div class="merry">
<table >
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
  </tr>
  <% @users.each do |user| %>
   <tr>
    <td><%=user.first_name%></td>
    <td><%=user.last_name%></td>
    <td><%=user.email%></td>
    <td><button><%= link_to('show user', user_path(user),:class => 'action show') %></button></td>
    <td><button><%= link_to('edit user', edit_user_path(user),:class => 'action edit') %></button></td>
    <td><button><%= link_to('delete user', delete_user_path(user),:class => 'action delete') %></button></td>
  </tr>
  <% end %>
</table>
</div>

<button><%= link_to('Create new user', new_user_path(@user),:class => 'action edit') %></button>
<br />
<br />
<br />

<button><%= link_to('Game page', :controller => 'game', :action => 'start')%></button>

app/views/users/new.html.erb
<h1>Users#new</h1>
<h1>Edit your info</h1>
<%= link_to('<< Back to list', users_path) %>
<%= form_for (@user) do |f| %>
<%# Using Partial form for shared html _form%>
<%= render(:partial => 'forms', :locals => {:f => f}) %>
<div class='form-buttons'>
  <%= f.submit('Create new user')%>
</div>
<% end %> 

app/views/users/show.html.erb
<h1>Users Details</h1>
<%= link_to('<< Back to list', users_path) %>

<table>
  <tr>
    <th>Name</th>
    <td><%= "#{@user.first_name} #{@user.last_name}"%></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @user.created_at%></td>
  </tr>
  <tr>
    <th>Updated at</th>
    <td><%= @user.updated_at%></td>
  </tr>
  <tr>
    <th>User email</th>
    <td><%= @user.email%></td>
  </tr>
</table>